name: McPlugin
main: nl.rmoesbergen.mcplugin.McPlugin
version: 1.0
commands:
   devil:
      description: Toggle devil mode
      usage: /devil
   unfreeze:
      description: Escape from camera mode
      usage: /unfreeze