name: ExplosiveEggs
main: nl.rmoesbergen.ExplosiveEggs
version: 1.0
api-version: 1.16
commands:
   devil:
      description: Toggle devil mode
      usage: /devil
   god:
      description: Toggle god mode
      usage: /god
   unfreeze:
      description: Escape from camera mode
      usage: /unfreeze
   nextcam:
      description: Switch to next security cam
      usage: /nextcam
permissions:
  explosiveeggs.throw:
    description: Allow player to throw explosive eggs
    default: false
  explosiveeggs.godmode:
    description: Allow godmode
    default: false
