name: ExplosiveEggs
main: nl.rmoesbergen.ExplosiveEggs
version: 1.0
api-version: 1.16
permissions:
  explosiveeggs.throw:
    description: Allow player to throw explosive eggs
    default: false
  explosiveeggs.jump:
    description: Allow high jumping and no fall damage
    default: false
depend: ["WorldEdit"]
