name: McPlugin
main: nl.rmoesbergen.mcplugin.McPlugin
version: 1.0
commands:
   devil:
      description: Toggle devil mode
      usage: /devil
   god:
      description: Toggle god mode
      usage: /god
   unfreeze:
      description: Escape from camera mode
      usage: /unfreeze
   nextcam:
      description: Switch to next security cam
      usage: /nextcam